// This source code is subject to the terms of the Mozilla Public License 2.0
// at https://mozilla.org/MPL/2.0/
// © Stonespb

//@version=5
strategy("SV Strategy", overlay=true)

////////////////////////////////////////////////////////////////////////////////
// EMA plots
shortest = ta.ema(close, 5)
short = ta.ema(close, 30)
longer = ta.ema(close, 60)

plot(shortest, color = color.red, title="Shortest EMA")
plot(short, color = color.orange, title="Short EMA")
plot(longer, color = color.aqua, title="Longer EMA")

// Moving average, 2-line cross
fastLength = input.int(5, minval=1, title="Fast Length")
slowLength = input.int(30, minval=1, title="Slow Length")
mafast = ta.ema(close, fastLength)
maslow = ta.ema(close, slowLength)

// Собираем индикаторы на 5 последних интервалах. Когда все "сложились" за период - ставим точку.

longEMACrosspoint = ta.crossover(mafast, maslow)
shortEMACrosspoint = ta.crossunder(mafast, maslow)

// Additional conditions

// Base Line (Kijun)
basePeriods = 26
donchian(len) => math.avg(ta.lowest(len), ta.highest(len))
baseLine = donchian(basePeriods)
plot(baseLine, color=color.blue, title="Base Line (Kijun)")
// TODO: cross in 7 last bars?

longBaseline = low > baseLine
shortBaseline = high < baseLine

// TODO: Price should cross RSI 50 line in 3 last bars


isSatisfied(condition) =>
    result = false
    for i = 0 to 4
        if condition[i]
            result := true
            break
    result

shouldTriggerLong = isSatisfied(longEMACrosspoint) and isSatisfied(longBaseline)
shouldTriggerShort = isSatisfied(shortEMACrosspoint) and isSatisfied(shortBaseline)

if (shouldTriggerLong)
    strategy.entry("SV Long", strategy.long, comment="L")
if (shouldTriggerShort)
    strategy.entry("SV Short", strategy.short, comment="S")
